### ISSUE TITLE
Pentaho Data Integration 6.1.0

### ISSUE THREAD

**Issue by petchadj** [zhicwu/cassandra-jdbc-driver#1]
Can you upload a screenshot or tell us how to setup for the Pentaho Data Integration DB connection? Couldn't get it to work. Thanks!

We're on DSE 5.0 + PDI 6.1.0

**Comment by zhicwu** [comment]
Thanks for reminding me to document this - will work this out soon :)

In the meantime, please try the instructions below on PDI(assume you opened a transformation):
**1) Create a database connection**
Connection Type: Generic database
Connection URL: jdbc:c*://<hostname>/system
Driver Class: com.github.cassandra.jdbc.CassandraDriver
User Name: cassandra
Password: cassandra

**2) Add a table input and see if it works**
First set connection to what you just created, Click "Get SQL select statement..." and then you should see schema defined in DSE. Alternatively, enter the following CQL and click Preview, you should see at least one record there.
```sql
SELECT * FROM local
```
Let me know if this works and in case you run into any issue, post a screenshot or detailed error message and I'll happy to help.

**Comment by petchadj** [comment]
Yup, that did the trick! Thanks for the quick response.
