### ISSUE TITLE
DataImportHandlerException: Unable to execute query

### ISSUE THREAD

**Issue by BhargavaRavaliKoganti** [zhicwu/cassandra-jdbc-driver#6]
Cassandra - 3.10
Java - 8
JDBC - 0.6.2
Solr - 6.6.0

I'm trying to integrate solr and cassandra latest versions. I'm getting exception like:

`Exception while processing: test document : SolrInputDocument(fields: []):org.apache.solr.handler.dataimport.DataImportHandlerException: Unable to execute query: SELECT id,org,name,dep,place,sal from tutor Processing Document # 1
	at org.apache.solr.handler.dataimport.DataImportHandlerException.wrapAndThrow(DataImportHandlerException.java:69)
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.<init>(JdbcDataSource.java:327)
	at org.apache.solr.handler.dataimport.JdbcDataSource.createResultSetIterator(JdbcDataSource.java:288)
	at org.apache.solr.handler.dataimport.JdbcDataSource.getData(JdbcDataSource.java:283)
	at org.apache.solr.handler.dataimport.JdbcDataSource.getData(JdbcDataSource.java:52)
	at org.apache.solr.handler.dataimport.SqlEntityProcessor.initQuery(SqlEntityProcessor.java:59)
	at org.apache.solr.handler.dataimport.SqlEntityProcessor.nextRow(SqlEntityProcessor.java:73)
	at org.apache.solr.handler.dataimport.EntityProcessorWrapper.nextRow(EntityProcessorWrapper.java:267)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:475)
	at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:414)
	at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:329)
	at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:232)
	at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:415)
	at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:474)
	at org.apache.solr.handler.dataimport.DataImporter.lambda$runAsync$0(DataImporter.java:457)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.createStatement(JdbcDataSource.java:342)
	at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.<init>(JdbcDataSource.java:318)
	... 14 more `

Does the JDBC support for the latest version?

**Comment by zhicwu** [comment]
Not sure if this relates to #5, which was fixed in 0.6.3. Did you try 0.6.3? Do you have the full stack trace of that exception?

**Comment by zhicwu** [comment]
On a side note, why not use DSE or cassandra-lucene-index instead?

**Comment by BhargavaRavaliKoganti** [comment]
Yes I did try #5, it did not work out. That is the complete stack trace. I'm trying to figure out how it works so did not try for DSE. However, I tried with DSE drivers to connect but it did not work out.

**Comment by zhicwu** [comment]
Could you try [0.6.4-SNAPSHOT](https://github.com/zhicwu/cassandra-jdbc-driver/releases/download/0.6.4-SNAPSHOT/cassandra-jdbc-driver-0.6.4-SNAPSHOT-shaded.jar) instead? It works for me.

**Comment by BhargavaRavaliKoganti** [comment]
Thank you but, it is the same error again.

**Comment by zhicwu** [comment]
Hmm... mind to share simplified solr config and Cassandra schema so that I can reproduce the issue?

**Comment by BhargavaRavaliKoganti** [comment]
ya sure!

solrconfig.xml added these lines

`  <requestHandler name="/dataimport" class="solr.DataImportHandler">
    <lst name="defaults">
      <str name="config">sample-data-config.xml</str>
    </lst>
  </requestHandler>`

sample-data-config.xml

`<dataConfig>
	<dataSource type="JdbcDataSource" driver="com.github.cassandra.jdbc.CassandraDriver" url="jdbc:cassandra://127.0.0.1:9042/demo" autoCommit="true"/>
	<document name="content">
		<entity name="test" query="SELECT id,org,name,dep,place,sal from system_traces.tutor" autoCommit="true">
			<field column="id" name="id" />
			<field column="org" name="org" />
			<field column="name" name="name" />
			<field column="dep" name="dep" />
			<field column="place" name="place" />
			<field column="sal" name="sal" />
		</entity>
	</document>
</dataConfig>`

manageschema.xml added these lines

`<field name="id" type="string" indexed="true" stored="true" required="true" multiValued="false" />
    <field name="org" type="string" indexed="true" stored="true" required="true" />
    <field name="dep" type="string" indexed="true" stored="true" required="true" />
    <field name="place" type="string" indexed="true" stored="true" required="true" />
    <field name="sal" type="string" indexed="true" stored="true" required="true" /> 
    <field name="name" type="string" indexed="true" stored="true" required="true"/>`

**Comment by BhargavaRavaliKoganti** [comment]
Please have a look at [this](https://stackoverflow.com/questions/44918135/datastax-driver-for-cassandra-and-solr-integration) as you asked me why not use DSE.

**Comment by BhargavaRavaliKoganti** [comment]
hey, I figured it out. The problem was with url. URL is "jdbc:c*://127.0.0.1:9042/demo"

**Comment by zhicwu** [comment]
Thanks for confirming this. I wasn't able to reproduce the issue on my side.
Anyway, I'll publish 0.6.4 release to include the fix tomorrow.

**Comment by BhargavaRavaliKoganti** [comment]
Is it possible to change the row limit to infinite (in CassandraConfiguration.java file)? As it fails to fetch the data, if I have huge data in my table(around 1000000 rows). If we definitely need to give a limit, why it is so? What would happen if we don't limit the rows?

**Comment by zhicwu** [comment]
You could try a query like below:
```sql
// set no_limit = true
select * from logs
```
Or add ` -Dcassandra.jdbc.driver.config=/usr/local/private/new_config.yaml` to use your own [config.yaml](https://github.com/zhicwu/cassandra-jdbc-driver/blob/master/src/main/resources/config.yaml)

Cassandra is good at random query and it's not recommended to query all rows from a large table - might be OK when the cluster has only one node.

**Comment by BhargavaRavaliKoganti** [comment]
Thank you I gave the row limit in Solr data configuration file. Now I'm able to fetch all records. And I'm trying to query from Solr not Cassandra. So, I need all the records.

**Comment by BhargavaRavaliKoganti** [comment]
Can you please explain what is that update in your driver making it compatible with the latest versions also, not the features? Is it a type 3 driver?

**Comment by zhicwu** [comment]
It's type 4. It's just a minor change to fix wrong assumption when dealing with connection parameters passed to the driver. I'll make a formal release to include this bug fix in weekend.

**Comment by BhargavaRavaliKoganti** [comment]
If suppose I want to work on this driver for Production purpose what needs to be done? Where and how do I have to start it?As I am interested in the project Solr+Cassandra.

**Comment by BhargavaRavaliKoganti** [comment]
If suppose I want to work on this driver for Production purpose what needs to be done? Where and how do I have to start it?As I am interested in the project Solr+Cassandra.

**Comment by zhicwu** [comment]
You can use it for production, but I don't recommend. It's not about the JDBC driver itself, it's about the approach getting Cassandra data indexed. I still think you should use either DSE or [cassandra-lucene-index](https://github.com/Stratio/cassandra-lucene-index), or even elasticsearch, for near-real time indexing.
