### ISSUE TITLE
IntelliJ IDEA integration

### ISSUE THREAD

**Issue by emartynov** [zhicwu/cassandra-jdbc-driver#7]
Do you know if driver is possible to use for custom jdbc connection within InteliJ IDEA?

If so what would be the connection params?

**Comment by zhicwu** [comment]
I use [DBeaver](https://dbeaver.jkiss.org) but it works in IDEA too. It’s a jdbc driver after all.

Basically, you create a new driver in IDEA and then a data source from it with connection URL like below(assume you have a cluster with 3 nodes: c1.test.org, c2.test.org and c3.test.org):
- jdbc:c*://c1.test.org/system
- jdbc:c*://c1.test.org,c2.test.org,c3.test.org/system

Detailed connection parameters(and default values) can be found in Advanced tab when creating/editing data source.
